### ISSUE TITLE
启动后没有任何反应也不报错

### ISSUE THREAD

**Issue by 1011382654** [zhinjs/qq-official-bot#65]
填不填appid secret 都一样
 node v18.12.1 
官方模块正常 qq-guild-bot: "^2.9.5"
![QQ_1723020792011](https://github.com/user-attachments/assets/7235bb18-849b-480a-9070-7aa4aecc4154)

**Comment by lc-cn** [comment]
等等，你包名不对吧，是qq-official-bot，而且你这不是debug模式么？
